flowchart BT
    subgraph Legend
        direction LR
        done(Done):::done --- todo(To do):::todo
    end
    subgraph Status
        direction LR
        sendsms(Send SMS):::done --- sendsms1(Single message):::done
        sendsms(Send SMS):::done --- sendsms2(Campaign):::done
        sendsms(Send SMS):::done --- sendsms3(Campaign with list):::done
        sendsms(Send SMS):::done --- sendsms4(Simulate a single message):::done
        sendsms(Send SMS):::done --- sendsms5(Simulate a campaign):::done
        sendsms(Send SMS):::done --- sendsms6(Cancel a campaign):::done
        sendsms(Send SMS):::done --- sendsms7(Short URL):::done
        campaigns(Campaigns):::done --- campaigns1(Get campaigns history):::done
        campaigns(Campaigns):::done --- campaigns2(Get campaign):::done
        campaigns(Campaigns):::done --- campaigns3(Blacklist the NPAI of a campaign):::done
        campaigns(Campaigns):::done --- campaigns4(Get the STOPs of a campaign):::done
        campaigns(Campaigns):::done --- campaigns5(Get the NPAIs of a campaign):::done
        campaigns(Campaigns):::done --- campaigns6(Get the replies of a campaign):::done
        lists(Lists):::done --- lists1(Create list):::done
        lists(Lists):::done --- lists2(Clear list):::done
        lists(Lists):::done --- lists3(Get lists):::done
        lists(Lists):::done --- lists4(Get list):::done
        lists(Lists):::done --- lists5(Delete list):::done
        lists(Lists):::done --- lists6(Blacklist):::done
        lists(Lists):::done --- lists7(NPAI):::done
        cont(Contacts):::done --- cont1(Insert into a list):::done
        cont(Contacts):::done --- cont2(Deduplicate list):::done
        cont(Contacts):::done --- cont3(Remove a contact):::done
        cont(Contacts):::done --- cont4(Update a contact):::done
        cont(Contacts):::done --- cont5(Insert into the blacklist):::done
        cont(Contacts):::done --- cont6(Insert into the NPAI list):::done
        accmgmt(Account Managing):::todo --- accmgmt1(Credits):::todo
        accmgmt(Account Managing):::todo --- accmgmt2(Create an account):::todo
        accmgmt(Account Managing):::todo --- accmgmt3(Retrieve account):::todo
        accmgmt(Account Managing):::todo --- accmgmt4(Retrieve sub-accounts):::todo
        accmgmt(Account Managing):::todo --- accmgmt5(Retrieve a sub-account):::todo
        accmgmt(Account Managing):::todo --- accmgmt6(Lock sub-account):::todo
        accmgmt(Account Managing):::todo --- accmgmt7(Unlock sub-account):::todo
        accmgmt(Account Managing):::todo --- accmgmt8(Transfer credits):::todo
        accmgmt(Account Managing):::todo --- accmgmt9(Data retention):::todo
        accmgmt9(Data retention):::todo --- dataretentionget(Get):::todo
        accmgmt9(Data retention):::todo --- dataretentionupdate(Update):::todo
        notif(Notifications):::todo --- notif1(Balance):::todo
        notif1(Balance):::todo --- notifget(Get):::done
        notif1(Balance):::todo --- notifupdate(Update):::todo
        invoices(Invoices):::todo --- invoices1(Get invoices):::todo
        invoices(Invoices):::todo --- invoices2(Get invoice):::todo
        invoices(Invoices):::todo --- invoices3(Download invoice):::todo
        apitoken(API Token):::todo --- apitoken1(Create a token):::todo
        apitoken(API Token):::todo --- apitoken2(Retrieve tokens):::todo
        apitoken(API Token):::todo --- apitoken3(Delete a token):::todo
        hlrlookup(HLR Lookup):::todo
        webhooks(Webhooks):::todo
        webhooks(Webhooks):::todo --- webhooks1(List of webhooks):::todo
        webhooks1(List of webhooks):::todo --- listofwebhooks1(Delivery reports):::todo
        webhooks1(List of webhooks):::todo --- listofwebhooks2(Replies):::todo
        webhooks1(List of webhooks):::todo --- listofwebhooks3(Stops):::todo
        webhooks1(List of webhooks):::todo --- listofwebhooks4(Clickers):::todo
        webhooks1(List of webhooks):::todo --- listofwebhooks5(Balance Alert):::todo
        webhooks(Webhooks):::todo --- webhooks2(Create a webhook):::todo
        webhooks(Webhooks):::todo --- webhooks3(Retrieve webhooks):::todo
        webhooks(Webhooks):::todo --- webhooks4(Update a webhook):::todo
        webhooks(Webhooks):::todo --- webhooks5(Delete a webhook):::todo
    end
    classDef done fill:#80CBC4,stroke-opacity:0;
    classDef todo fill:#E3F2FD,stroke-opacity:0;