flowchart BT
    subgraph Legend
        direction LR
        done(Done):::done --- todo(To do):::todo
    end
    subgraph Status
        direction LR
        sendsms(Send SMS):::done --- sendsms1(Single message):::done
        sendsms(Send SMS):::done --- sendsms2(Campaign):::done
        sendsms(Send SMS):::done --- sendsms3(Campaign with list):::done
        sendsms(Send SMS):::done --- sendsms4(Simulate a single message):::done
        sendsms(Send SMS):::done --- sendsms5(Simulate a campaign):::done
        sendsms(Send SMS):::done --- sendsms6(Cancel a campaign):::done
        sendsms(Send SMS):::done --- sendsms7(Short URL):::done
        campaigns(Campaigns):::done --- campaigns1(Get campaigns history):::done
        campaigns(Campaigns):::done --- campaigns2(Get campaign):::done
        campaigns(Campaigns):::done --- campaigns3(Blacklist the NPAI of a campaign):::done
        campaigns(Campaigns):::done --- campaigns4(Get the STOPs of a campaign):::done
        campaigns(Campaigns):::done --- campaigns5(Get the NPAIs of a campaign):::done
        campaigns(Campaigns):::done --- campaigns6(Get the replies of a campaign):::done
        lists(Lists):::done --- lists1(Create list):::done
        lists(Lists):::done --- lists2(Clear list):::done
        lists(Lists):::done --- lists3(Get lists):::done
        lists(Lists):::done --- lists4(Get list):::done
        lists(Lists):::done --- lists5(Delete list):::done
        lists(Lists):::done --- lists6(Blacklist):::done
        lists(Lists):::done --- lists7(NPAI):::done
        cont(Contacts):::done --- cont1(Insert into a list):::done
        cont(Contacts):::done --- cont2(Deduplicate list):::done
        cont(Contacts):::done --- cont3(Remove a contact):::done
        cont(Contacts):::done --- cont4(Update a contact):::done
        cont(Contacts):::done --- cont5(Insert into the blacklist):::done
        cont(Contacts):::done --- cont6(Insert into the NPAI list):::done
        accmgmt(Account Managing):::done --- accmgmt1(Credits):::done
        accmgmt(Account Managing):::done --- accmgmt2(Create an account):::done
        accmgmt(Account Managing):::done --- accmgmt3(Retrieve account):::done
        accmgmt(Account Managing):::done --- accmgmt4(Retrieve sub-accounts):::done
        accmgmt(Account Managing):::done --- accmgmt5(Retrieve a sub-account):::done
        accmgmt(Account Managing):::done --- accmgmt6(Lock sub-account):::done
        accmgmt(Account Managing):::done --- accmgmt7(Unlock sub-account):::done
        accmgmt(Account Managing):::done --- accmgmt8(Transfer credits):::done
        accmgmt(Account Managing):::done --- accmgmt9(Data retention):::todo
        accmgmt9(Data retention):::done --- dataretentionget(Get):::done
        accmgmt9(Data retention):::done --- dataretentionupdate(Update):::done
        notif(Notifications):::done --- notif1(Balance):::done
        notif1(Balance):::done --- notifget(Get):::done
        notif1(Balance):::done --- notifupdate(Update):::done
        invoices(Invoices):::done --- invoices1(Get invoices):::done
        invoices(Invoices):::done --- invoices2(Get invoice):::done
        invoices(Invoices):::done --- invoices3(Download invoice):::done
        apitoken(API Token):::done --- apitoken1(Create a token):::done
        apitoken(API Token):::done --- apitoken2(Retrieve tokens):::done
        apitoken(API Token):::done --- apitoken3(Delete a token):::done
        hlrlookup(HLR Lookup):::done
        webhooks(Webhooks):::done --- webhooks2(Create a webhook):::done
        webhooks(Webhooks):::done --- webhooks3(Retrieve webhooks):::done
        webhooks(Webhooks):::done --- webhooks4(Retrieve a single webhook):::done
        webhooks(Webhooks):::done --- webhooks5(Update a webhook):::done
        webhooks(Webhooks):::done --- webhooks6(Delete a webhook):::done
    end
    classDef done fill:#80CBC4,stroke-opacity:0;
    classDef todo fill:#E3F2FD,stroke-opacity:0;